services:
  mesh-api:
    image: mrtbot/mesh-api:latest
    container_name: mesh-api
    ports:
      - "5000:5000"
    privileged: true
   # environment:  // UNCOMMENT IF USING SERIAL AND MODIFY FOR YOUR MACHINE.  
   #   - MESH_INTERFACE=/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
    volumes:
   #   - /dev/serial/by-id:/dev/serial/by-id:ro  //UNCOMMENT IF USING SERIAL.
   #   - /dev:/dev  //UNCOMMENT IF USING SERIAL.
      # Mount config files
      - ./mesh-api/config/config.json:/app/config.json
      - ./mesh-api/config/commands_config.json:/app/commands_config.json
      - ./mesh-api/config/motd.json:/app/motd.json

      # Mount log files
      - ./mesh-api/logs/messages.log:/app/messages.log
      - ./mesh-api/logs/messages_archive.json:/app/messages_archive.json
      - ./mesh-api/logs/script.log:/app/script.log

    restart: unless-stopped
  #  healthcheck:  // OPTIONAL SERIAL DEVICE HEALTH CHECK - MODIFY FOR YOUR SERIAL DEVICE.
  #    test: ["CMD", "ls", "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"]
  #    interval: 30s
  #    retries: 3
  #    timeout: 5s
